
/****************************************************************************
 *
 *   Copyright (C) 2022 bsvtgc@gmail.com. All rights reserved.
 *   Author: Vincent <bsvtgc@gmail.com>
 *
 ****************************************************************************/

.ifndef _HIFIVE1_REVB_SRC_INC_CSR_INC_

.equiv _HIFIVE1_REVB_SRC_INC_CSR_INC_, 1

.equiv MIE_MEIE, 0x800 /* Bit 11 */
.equiv MSTATUS_MIE, 0x8 /* Bit 3 */

.endif
