
/****************************************************************************
 *
 *   Copyright (C) 2022 bsvtgc@gmail.com. All rights reserved.
 *   Author: Vincent <bsvtgc@gmail.com>
 *
 ****************************************************************************/

.ifndef _HIFIVE1_REVB_SRC_INC_MMAP_INC_
.equiv _HIFIVE1_REVB_SRC_INC_MMAP_INC_, 1

.equiv PLIC_BASE, 0x0C000000 /* Implementation specific */
.equiv GPIO_BASE, 0x10012000  /* GPIO Base address */
.equiv UART1_BASE, 0x10023000 /* UART1 Base Address */

.endif

