
/****************************************************************************
 *
 *   Copyright (C) 2022 bsvtgc@gmail.com. All rights reserved.
 *   Author: Vincent <bsvtgc@gmail.com>
 *
 ****************************************************************************/

.equiv UART_TXDATA_OFFSET, 0x00
.equiv UART_RXDATA_OFFSET, 0x04
.equiv UART_TXCTRL_OFFSET, 0x08
.equiv UART_RXCTRL_OFFSET, 0x0C
.equiv UART_INTR_EN_OFFSET, 0x10
.equiv UART_INTR_PEND_OFFSET, 0x14
.equiv UART_BAUD_DIV_OFFSET, 0x18
